version: '3.8'
services:
  nginx:
    image: nginx:stable
    ports:
      - "8080:80"
      # Ensure the read and write access
    volumes:
      - ./site/:/var/www/html/:rw
      - ./conf/nginx/conf.d:/etc/nginx/conf.d/:ro
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./log/nginx/:/var/log/nginx/:rw
    networks:
      - noyr_share

  php56:
    build: ./php/php56/
    expose:
      - "9000"
    volumes:
      - ./site/:/var/www/html/:rw
      - ./conf/php/php.ini:/usr/local/etc/php/php.ini:ro
      - ./conf/php/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf:rw
      - ./log/php-fpm/:/var/log/php-fpm/:rw
    networks:
      - noyr_share

  php74:
    build: ./php/php74/
    expose:
      - "9000"
    volumes:
      - ./site/:/var/www/html/:rw
      - ./conf/php/php.ini:/usr/local/etc/php/php.ini:ro
      - ./conf/php/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf:rw
      - ./log/php-fpm/:/var/log/php-fpm/:rw
    networks:
      - noyr_share

  php81:
    build: ./php/php81/
    expose:
      - "9000"
    volumes:
      - ./site/:/var/www/html/:rw
      - ./conf/php/php.ini:/usr/local/etc/php/php.ini:ro
      - ./conf/php/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf:rw
      - ./log/php-fpm/:/var/log/php-fpm/:rw
    networks:
      - noyr_share

  mariadb:
    image: mariadb:10.9.4
    ports:
      - "3306:3306"
    volumes:
      - ./conf/mariadb/my.cnf:/etc/mariadb/my.cnf:ro
      - ./mariadb/:/var/lib/mariadb/:rw
      - ./log/mariadb/:/var/log/mariadb/:rw
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    networks:
      - noyr_share

networks:
  noyr_share:
    driver: bridge
