version: '3.8'

services:
  nginx:
    container_name: php_dev_nginx
    image: nginx:alpine
    restart: always
    ports:
      - 8081:80
    volumes:
      - public_html:/public_html
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/log:/var/log/nginx
  php81:
    container_name: php_dev_php81
    image: php:8.1-fpm
    restart: always
    build: 
      context: ./ 
      dockerfile: ./php/Dockerfile.php81
    depends_on:
      - nginx
    volumes:
      - public_html:/public_html
      #~ - ./php:/usr/local/etc/php
      - ./php/conf/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./php/conf/php.ini:/usr/local/etc/php/php.ini
  php74:
    container_name: php_dev_php74
    image: php:7.4.29-fpm
    restart: always
    build: 
      context: ./ 
      dockerfile: ./php/Dockerfile.php74
    depends_on:
      - nginx
    volumes:
      - public_html:/public_html
      #~ - ./php:/usr/local/etc/php
      - ./php/conf/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./php/conf/php.ini:/usr/local/etc/php/php.ini
  php56:
    container_name: php_dev_php56
    image: php:5.6-fpm
    restart: always
    build: 
      context: ./ 
      dockerfile: ./php/Dockerfile.php56
    depends_on:
      - nginx
    volumes:
      - public_html:/public_html
      #~ - ./php:/usr/local/etc/php
      - ./php/conf/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./php/conf/php.ini:/usr/local/etc/php/php.ini
  db:
    container_name: php_dev_mariadb
    image: mariadb:10.9.4
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3301:3306
    volumes:
      - db_data:/var/lib/mariadb
  adminer:
    container_name: php_dev_adminer
    image: adminer
    restart: always
    links:
      - db:php_dev_database
    ports:
      - 8082:8080
volumes:
  public_html:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/public_html
      o: bind
  db_data:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/mariadb
      o: bind
